version: '3.1'
services:
  db:
    image: mysql
    container_name: springessentials_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    ports:
    - "9090:3306"
    volumes:
      - vitorlucas_data:/var/lib/mysql

volumes:
  vitorlucas_data:
